import { MigrationInterface, QueryRunner } from 'typeorm';
import { Service } from 'typedi';

// Staged baseline migration for the dev-history squash.
// This lives outside the active migrations path until the cutover happens.
@Service()
export class BaselineCoreSchema1800000000000 implements MigrationInterface {
  name = 'BaselineCoreSchema1800000000000';

  private readonly createStatements = [
    `CREATE TABLE \`activity_exports\` (
  \`id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`scope\` varchar(32) NOT NULL,
  \`format\` varchar(16) NOT NULL,
  \`status\` varchar(16) NOT NULL DEFAULT 'Ready',
  \`file_name\` varchar(255) NOT NULL,
  \`content_type\` varchar(100) NOT NULL,
  \`exported_count\` int unsigned NOT NULL DEFAULT '0',
  \`filters_json\` json DEFAULT NULL,
  \`content\` longtext,
  \`expires_at\` timestamp NULL DEFAULT NULL,
  \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updatedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  \`storage_path\` varchar(512) DEFAULT NULL,
  \`error_message\` varchar(255) DEFAULT NULL,
  \`filter_signature\` varchar(64) DEFAULT NULL,
  \`worker_id\` varchar(191) DEFAULT NULL,
  \`processing_started_at\` timestamp NULL DEFAULT NULL,
  \`repaired_at\` timestamp NULL DEFAULT NULL,
  \`repair_reason\` text,
  PRIMARY KEY (\`id\`),
  KEY \`idx_activity_exports_user_created_at\` (\`user_id\`,\`createdAt\`),
  KEY \`idx_activity_exports_user_status_created_at\` (\`user_id\`,\`status\`,\`createdAt\`),
  KEY \`idx_activity_exports_status_created_at\` (\`status\`,\`createdAt\`),
  KEY \`idx_activity_exports_expires_at\` (\`expires_at\`),
  KEY \`idx_activity_exports_user_status_signature\` (\`user_id\`,\`status\`,\`filter_signature\`,\`expires_at\`),
  KEY \`idx_activity_exports_status_processing_started_at\` (\`status\`,\`processing_started_at\`),
  KEY \`idx_activity_exports_worker_status_updated_at\` (\`worker_id\`,\`status\`,\`updatedAt\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`activity_logs\` (
  \`id\` varchar(36) NOT NULL,
  \`type\` varchar(50) NOT NULL,
  \`title\` varchar(255) NOT NULL,
  \`status\` varchar(30) NOT NULL,
  \`actor\` varchar(100) DEFAULT NULL,
  \`symbol\` varchar(50) DEFAULT NULL,
  \`route\` varchar(100) DEFAULT NULL,
  \`description\` text,
  \`referenceId\` varchar(100) DEFAULT NULL,
  \`stream\` varchar(50) DEFAULT NULL,
  \`related\` varchar(100) DEFAULT NULL,
  \`flags\` json DEFAULT NULL,
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`user_id\` varchar(191) NOT NULL,
  \`read_at\` timestamp NULL DEFAULT NULL,
  \`correlation_id\` varchar(191) DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`idx_activity_logs_status_created_at\` (\`status\`,\`createdAt\`),
  KEY \`idx_activity_logs_stream_created_at\` (\`stream\`,\`createdAt\`),
  KEY \`idx_activity_logs_user_created_at\` (\`user_id\`,\`createdAt\`),
  KEY \`idx_activity_logs_user_stream_created_at\` (\`user_id\`,\`stream\`,\`createdAt\`),
  KEY \`idx_activity_logs_user_status_created_at\` (\`user_id\`,\`status\`,\`createdAt\`),
  KEY \`idx_activity_logs_user_read_created_at\` (\`user_id\`,\`read_at\`,\`createdAt\`),
  KEY \`idx_activity_logs_user_correlation_created_at\` (\`user_id\`,\`correlation_id\`,\`createdAt\`),
  KEY \`idx_activity_logs_user_route_created_at\` (\`user_id\`,\`route\`,\`createdAt\`),
  KEY \`idx_activity_logs_user_reference_created_at\` (\`user_id\`,\`referenceId\`,\`createdAt\`),
  KEY \`idx_activity_logs_user_related_created_at\` (\`user_id\`,\`related\`,\`createdAt\`),
  KEY \`idx_activity_logs_user_type_created_at\` (\`user_id\`,\`type\`,\`createdAt\`),
  KEY \`idx_activity_logs_user_symbol_created_at\` (\`user_id\`,\`symbol\`,\`createdAt\`),
  FULLTEXT KEY \`ft_activity_logs_search\` (\`type\`,\`title\`,\`status\`,\`actor\`,\`symbol\`,\`route\`,\`referenceId\`,\`stream\`,\`related\`,\`description\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`activity_saved_views\` (
  \`id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`name\` varchar(100) NOT NULL,
  \`description\` text,
  \`is_default\` tinyint(1) NOT NULL DEFAULT '0',
  \`view\` varchar(16) NOT NULL DEFAULT 'feed',
  \`group_by\` varchar(16) DEFAULT NULL,
  \`sort_by\` varchar(16) NOT NULL DEFAULT 'time',
  \`sort_order\` varchar(8) NOT NULL DEFAULT 'desc',
  \`read_state\` varchar(16) NOT NULL DEFAULT 'all',
  \`filters_json\` json DEFAULT NULL,
  \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updatedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  KEY \`idx_activity_saved_views_user_created_at\` (\`user_id\`,\`createdAt\`),
  KEY \`idx_activity_saved_views_user_default_updated_at\` (\`user_id\`,\`is_default\`,\`updatedAt\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`alerts\` (
  \`id\` varchar(36) NOT NULL,
  \`severity\` varchar(20) NOT NULL,
  \`channel\` varchar(50) NOT NULL,
  \`symbol\` varchar(50) NOT NULL,
  \`message\` varchar(255) NOT NULL,
  \`route\` varchar(100) DEFAULT NULL,
  \`status\` varchar(20) NOT NULL,
  \`source\` varchar(100) DEFAULT NULL,
  \`urgency\` varchar(50) DEFAULT NULL,
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`user_id\` varchar(191) NOT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`idx_alerts_severity_created_at\` (\`severity\`,\`createdAt\`),
  KEY \`idx_alerts_status_created_at\` (\`status\`,\`createdAt\`),
  KEY \`idx_alerts_user_status_channel_source_created_at\` (\`user_id\`,\`status\`,\`channel\`,\`source\`,\`createdAt\`),
  KEY \`idx_alerts_user_created_at\` (\`user_id\`,\`createdAt\`),
  KEY \`idx_alerts_user_status_created_at\` (\`user_id\`,\`status\`,\`createdAt\`),
  KEY \`idx_alerts_user_severity_created_at\` (\`user_id\`,\`severity\`,\`createdAt\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`alert_actions\` (
  \`id\` varchar(36) NOT NULL,
  \`alertId\` varchar(36) NOT NULL,
  \`actionType\` varchar(30) NOT NULL,
  \`target\` varchar(50) DEFAULT NULL,
  \`note\` text,
  \`actor\` varchar(100) DEFAULT NULL,
  \`metadata\` json DEFAULT NULL,
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`user_id\` varchar(191) NOT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`idx_alert_actions_alert_created_at\` (\`alertId\`,\`createdAt\`),
  CONSTRAINT \`FK_c780ec3aeeeca2e97799c242a13\` FOREIGN KEY (\`alertId\`) REFERENCES \`alerts\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`app_settings\` (
  \`notifyEmail\` tinyint NOT NULL DEFAULT '1',
  \`notifyInApp\` tinyint NOT NULL DEFAULT '1',
  \`confirmDestructive\` tinyint NOT NULL DEFAULT '1',
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`user_id\` char(36) NOT NULL,
  \`id\` int NOT NULL AUTO_INCREMENT,
  \`notificationChannel\` varchar(16) NOT NULL DEFAULT 'both',
  \`notificationSeverity\` varchar(16) NOT NULL DEFAULT 'all',
  \`escalationRoute\` varchar(24) NOT NULL DEFAULT 'risk-review',
  \`escalationSlaMinutes\` int NOT NULL DEFAULT '15',
  \`timezone\` varchar(64) NOT NULL DEFAULT 'UTC',
  \`backtestPromotionRules\` json DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_app_settings_user_id\` (\`user_id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`asset_price\` (
  \`broker_asset_id\` char(36) NOT NULL,
  \`symbol\` varchar(100) NOT NULL,
  \`source_symbol\` varchar(100) DEFAULT NULL,
  \`price\` decimal(30,12) NOT NULL,
  \`source\` varchar(30) NOT NULL,
  \`retrieved_at\` datetime NOT NULL,
  \`updated_at\` datetime NOT NULL,
  PRIMARY KEY (\`broker_asset_id\`),
  KEY \`idx_asset_price_source_symbol\` (\`source\`,\`symbol\`),
  KEY \`idx_asset_price_symbol\` (\`symbol\`),
  KEY \`idx_asset_price_retrieved_at\` (\`retrieved_at\`),
  KEY \`idx_asset_price_updated_at\` (\`updated_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`assets\` (
  \`id\` char(36) NOT NULL DEFAULT (uuid()),
  \`source\` varchar(50) NOT NULL,
  \`externalId\` varchar(255) NOT NULL,
  \`symbol\` varchar(100) NOT NULL,
  \`name\` varchar(255) NOT NULL,
  \`status\` varchar(20) NOT NULL DEFAULT 'active',
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uq_assets_source_external_id\` (\`source\`,\`externalId\`),
  KEY \`idx_assets_symbol_name\` (\`symbol\`,\`name\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`automation_cursors\` (
  \`id\` char(36) NOT NULL,
  \`automation_id\` char(36) NOT NULL,
  \`user_id\` char(36) NOT NULL,
  \`symbol\` varchar(64) NOT NULL,
  \`timeframe\` varchar(16) NOT NULL,
  \`last_evaluated_signal_time\` timestamp NULL DEFAULT NULL,
  \`last_triggered_signal_time\` timestamp NULL DEFAULT NULL,
  \`last_run_id\` char(36) DEFAULT NULL,
  \`last_status\` varchar(32) DEFAULT NULL,
  \`meta_json\` json DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_automation_cursors_automation_symbol_timeframe\` (\`automation_id\`,\`symbol\`,\`timeframe\`),
  KEY \`idx_automation_cursors_user_updated_at\` (\`user_id\`,\`updated_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`automation_runs\` (
  \`id\` char(36) NOT NULL,
  \`automation_id\` char(36) NOT NULL,
  \`user_id\` char(36) NOT NULL,
  \`status\` varchar(32) NOT NULL,
  \`scheduled_for\` timestamp NULL DEFAULT NULL,
  \`started_at\` timestamp NOT NULL,
  \`finished_at\` timestamp NULL DEFAULT NULL,
  \`duration_ms\` int DEFAULT NULL,
  \`error_message\` text,
  \`meta_json\` text,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`worker_id\` varchar(191) DEFAULT NULL,
  \`last_progress_at\` timestamp NULL DEFAULT NULL,
  \`repaired_at\` timestamp NULL DEFAULT NULL,
  \`repair_reason\` text,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_automation_runs_automation_scheduled\` (\`automation_id\`,\`scheduled_for\`),
  KEY \`idx_automation_runs_automation_started\` (\`automation_id\`,\`started_at\`),
  KEY \`idx_automation_runs_user_started\` (\`user_id\`,\`started_at\`),
  KEY \`idx_automation_runs_status_scheduled\` (\`status\`,\`scheduled_for\`),
  KEY \`idx_automation_runs_status_last_progress_at\` (\`status\`,\`last_progress_at\`),
  KEY \`idx_automation_runs_worker_status_started_at\` (\`worker_id\`,\`status\`,\`started_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`automations\` (
  \`id\` varchar(36) NOT NULL,
  \`name\` varchar(255) NOT NULL,
  \`strategy\` varchar(255) NOT NULL,
  \`broker\` varchar(255) NOT NULL,
  \`market\` varchar(50) NOT NULL,
  \`trigger\` varchar(255) NOT NULL,
  \`status\` varchar(30) NOT NULL,
  \`lastRun\` timestamp NULL DEFAULT NULL,
  \`nextRun\` timestamp NULL DEFAULT NULL,
  \`accounts\` int unsigned NOT NULL DEFAULT '0',
  \`riskMode\` varchar(100) DEFAULT NULL,
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`config\` json DEFAULT NULL,
  \`user_id\` char(36) NOT NULL,
  \`automationType\` varchar(50) DEFAULT NULL,
  \`timeZone\` varchar(64) DEFAULT NULL,
  \`schedule\` json DEFAULT NULL,
  \`searchText\` varchar(512) DEFAULT NULL,
  \`sourceBacktestId\` varchar(64) DEFAULT NULL,
  \`scopeSymbol\` varchar(64) DEFAULT NULL,
  \`scopeTimeframe\` varchar(32) DEFAULT NULL,
  \`sourceTemplateId\` varchar(64) DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`idx_automations_user_status_updated_at\` (\`user_id\`,\`status\`,\`updatedAt\`),
  KEY \`idx_automations_user_market_updated_at\` (\`user_id\`,\`market\`,\`updatedAt\`),
  KEY \`idx_automations_status_next_run\` (\`status\`,\`nextRun\`),
  KEY \`idx_automations_user_scope_lookup\` (\`user_id\`,\`automationType\`,\`sourceBacktestId\`,\`scopeSymbol\`,\`scopeTimeframe\`),
  KEY \`idx_automations_user_source_template_updated_at\` (\`user_id\`,\`sourceTemplateId\`,\`updatedAt\`),
  FULLTEXT KEY \`ftx_automations_search_text\` (\`searchText\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`automation_alerts\` (
  \`id\` varchar(36) NOT NULL,
  \`automationId\` varchar(36) NOT NULL,
  \`message\` varchar(255) NOT NULL,
  \`severity\` varchar(20) NOT NULL,
  \`status\` varchar(20) NOT NULL,
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`meta_json\` text,
  PRIMARY KEY (\`id\`),
  KEY \`idx_automation_alerts_automation_created_at\` (\`automationId\`,\`createdAt\`),
  CONSTRAINT \`FK_9102852f768c2e490b909ac260f\` FOREIGN KEY (\`automationId\`) REFERENCES \`automations\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`automation_events\` (
  \`id\` varchar(36) NOT NULL,
  \`automationId\` varchar(36) NOT NULL,
  \`type\` varchar(100) NOT NULL,
  \`entity\` varchar(255) DEFAULT NULL,
  \`outcome\` varchar(100) DEFAULT NULL,
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`meta_json\` text,
  PRIMARY KEY (\`id\`),
  KEY \`idx_automation_events_automation_created_at\` (\`automationId\`,\`createdAt\`),
  CONSTRAINT \`FK_5ba3a37db3db68341f7d03e78c1\` FOREIGN KEY (\`automationId\`) REFERENCES \`automations\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`brokers\` (
  \`id\` char(36) NOT NULL,
  \`broker_key\` varchar(100) NOT NULL,
  \`name\` varchar(191) NOT NULL,
  \`category\` varchar(32) NOT NULL DEFAULT 'broker',
  \`status\` varchar(32) NOT NULL DEFAULT 'active',
  \`capabilities\` json DEFAULT NULL,
  \`account_config\` json DEFAULT NULL,
  \`integration_guide\` json DEFAULT NULL,
  \`diagnostics_config\` json DEFAULT NULL,
  \`provider_type\` varchar(32) NOT NULL DEFAULT 'broker',
  \`linked_exchange_key\` varchar(100) DEFAULT NULL,
  \`base_url\` varchar(255) DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`UQ_d67b5df33de65b86d24dbbd3b8f\` (\`broker_key\`),
  UNIQUE KEY \`uidx_brokers_broker_key\` (\`broker_key\`),
  UNIQUE KEY \`uidx_brokers_name\` (\`name\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`broker_assets\` (
  \`id\` varchar(36) NOT NULL,
  \`source\` varchar(50) NOT NULL,
  \`externalId\` varchar(255) NOT NULL,
  \`name\` varchar(255) NOT NULL,
  \`symbol\` varchar(100) NOT NULL,
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`assetId\` varchar(36) NOT NULL,
  \`broker_id\` char(36) DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uq_broker_assets_source_symbol\` (\`source\`,\`symbol\`),
  KEY \`FK_exchange_assets_broker_id\` (\`broker_id\`),
  KEY \`idx_broker_assets_source_symbol_name\` (\`source\`,\`symbol\`,\`name\`),
  KEY \`idx_broker_assets_broker_id\` (\`broker_id\`),
  KEY \`idx_broker_assets_source_external_id\` (\`source\`,\`externalId\`),
  KEY \`idx_broker_assets_source_asset_id\` (\`source\`,\`assetId\`),
  CONSTRAINT \`FK_exchange_assets_broker_id\` FOREIGN KEY (\`broker_id\`) REFERENCES \`brokers\` (\`id\`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`connections\` (
  \`id\` varchar(36) NOT NULL,
  \`name\` varchar(255) NOT NULL,
  \`broker\` varchar(255) DEFAULT NULL,
  \`type\` varchar(30) NOT NULL,
  \`status\` varchar(30) NOT NULL DEFAULT 'Idle',
  \`latency\` varchar(50) DEFAULT NULL,
  \`mode\` varchar(50) DEFAULT NULL,
  \`lastSyncAt\` timestamp NULL DEFAULT NULL,
  \`diagnosticSummary\` varchar(255) DEFAULT NULL,
  \`route\` varchar(100) DEFAULT NULL,
  \`scope\` varchar(100) DEFAULT NULL,
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`brokerKey\` varchar(100) NOT NULL,
  \`user_id\` char(36) DEFAULT NULL,
  \`broker_id\` char(36) DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`idx_connections_user_type_updated_at\` (\`user_id\`,\`type\`,\`updatedAt\`),
  KEY \`idx_connections_user_broker_id\` (\`user_id\`,\`broker_id\`),
  KEY \`FK_connections_broker_id\` (\`broker_id\`),
  KEY \`idx_connections_user_status_updated_at\` (\`user_id\`,\`status\`,\`updatedAt\`),
  CONSTRAINT \`FK_connections_broker_id\` FOREIGN KEY (\`broker_id\`) REFERENCES \`brokers\` (\`id\`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`broker_accounts\` (
  \`id\` varchar(36) NOT NULL,
  \`connectionId\` varchar(36) NOT NULL,
  \`brokerKey\` varchar(100) NOT NULL,
  \`accountKey\` varchar(100) NOT NULL,
  \`accountName\` varchar(255) NOT NULL,
  \`status\` varchar(30) NOT NULL,
  \`mode\` varchar(50) DEFAULT NULL,
  \`lastSyncAt\` timestamp NULL DEFAULT NULL,
  \`purpose\` varchar(255) DEFAULT NULL,
  \`capabilities\` varchar(255) DEFAULT NULL,
  \`isDefault\` tinyint NOT NULL DEFAULT '0',
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`settings\` json DEFAULT NULL,
  \`user_id\` char(36) DEFAULT NULL,
  \`broker_id\` char(36) DEFAULT NULL,
  \`default_owner_connection_key\` varchar(120) GENERATED ALWAYS AS ((case when (\`isDefault\` = 1) then concat(coalesce(\`user_id\`,_utf8mb4'__system__'),_utf8mb4'::',\`connectionId\`) else NULL end)) STORED,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_broker_accounts_user_account_key\` (\`user_id\`,\`accountKey\`),
  UNIQUE KEY \`uidx_broker_accounts_default_owner_connection\` (\`default_owner_connection_key\`),
  KEY \`idx_broker_accounts_user_status_updated_at\` (\`user_id\`,\`status\`,\`updatedAt\`),
  KEY \`idx_broker_accounts_user_connection_updated_at\` (\`user_id\`,\`connectionId\`,\`updatedAt\`),
  KEY \`idx_broker_accounts_user_broker_id\` (\`user_id\`,\`broker_id\`),
  KEY \`FK_broker_accounts_broker_id\` (\`broker_id\`),
  KEY \`FK_broker_accounts_connection_id\` (\`connectionId\`),
  CONSTRAINT \`FK_broker_accounts_broker_id\` FOREIGN KEY (\`broker_id\`) REFERENCES \`brokers\` (\`id\`) ON DELETE SET NULL,
  CONSTRAINT \`FK_broker_accounts_connection_id\` FOREIGN KEY (\`connectionId\`) REFERENCES \`connections\` (\`id\`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`email_deliveries\` (
  \`id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`alert_id\` char(36) DEFAULT NULL,
  \`recipient_email\` varchar(191) NOT NULL,
  \`subject\` varchar(255) NOT NULL,
  \`body\` text NOT NULL,
  \`channel\` varchar(50) NOT NULL,
  \`severity\` varchar(20) NOT NULL,
  \`route\` varchar(100) DEFAULT NULL,
  \`source\` varchar(100) DEFAULT NULL,
  \`status\` varchar(20) NOT NULL DEFAULT 'Queued',
  \`attempts\` int NOT NULL DEFAULT '0',
  \`last_error\` text,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  KEY \`idx_email_deliveries_status_created_at\` (\`status\`,\`created_at\`),
  KEY \`idx_email_deliveries_user_created_at\` (\`user_id\`,\`created_at\`),
  KEY \`idx_email_deliveries_status_updated_at\` (\`status\`,\`updated_at\`),
  KEY \`idx_email_deliveries_channel_created_at\` (\`channel\`,\`created_at\`),
  KEY \`idx_email_deliveries_severity_created_at\` (\`severity\`,\`created_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`exchanges\` (
  \`id\` char(36) NOT NULL,
  \`exchange_key\` varchar(100) NOT NULL,
  \`name\` varchar(191) NOT NULL,
  \`status\` varchar(32) NOT NULL DEFAULT 'active',
  \`base_url\` varchar(255) DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`UQ_c056666b6e873c3ce20ee0e050c\` (\`exchange_key\`),
  UNIQUE KEY \`uidx_exchanges_exchange_key\` (\`exchange_key\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`market_symbol_snapshots\` (
  \`symbol\` varchar(50) NOT NULL,
  \`asset_id\` varchar(36) DEFAULT NULL,
  \`name\` varchar(255) DEFAULT NULL,
  \`source\` varchar(100) DEFAULT NULL,
  \`last_price\` decimal(30,12) DEFAULT NULL,
  \`change_24h\` double DEFAULT NULL,
  \`volume_24h\` double DEFAULT NULL,
  \`high_24h\` decimal(30,12) DEFAULT NULL,
  \`low_24h\` decimal(30,12) DEFAULT NULL,
  \`liquidity_tier\` varchar(20) DEFAULT NULL,
  \`price_source\` varchar(50) DEFAULT NULL,
  \`snapshot_at\` datetime DEFAULT NULL,
  \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updatedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`symbol\`),
  KEY \`idx_market_symbol_snapshots_snapshot_at\` (\`snapshot_at\`),
  KEY \`idx_market_symbol_snapshots_liquidity_updated_at\` (\`liquidity_tier\`,\`updatedAt\`),
  KEY \`idx_market_symbol_snapshots_volume_24h\` (\`volume_24h\`),
  KEY \`idx_market_symbol_snapshots_change_24h\` (\`change_24h\`),
  KEY \`idx_market_symbol_snapshots_last_price\` (\`last_price\`),
  KEY \`idx_market_symbol_snapshots_liquidity_volume_24h\` (\`liquidity_tier\`,\`volume_24h\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`order_submission_requests\` (
  \`id\` char(36) NOT NULL,
  \`user_id\` char(36) NOT NULL,
  \`idempotency_key\` varchar(191) NOT NULL,
  \`request_hash\` char(64) NOT NULL,
  \`execution_mode\` varchar(32) NOT NULL,
  \`asset_id\` varchar(191) NOT NULL,
  \`broker_key\` varchar(100) DEFAULT NULL,
  \`account_id\` char(36) DEFAULT NULL,
  \`suggested_trade_id\` char(36) DEFAULT NULL,
  \`request_json\` json DEFAULT NULL,
  \`status\` varchar(32) NOT NULL DEFAULT 'in_progress',
  \`placement_state\` varchar(32) NOT NULL DEFAULT 'registered',
  \`broker_order_id\` varchar(191) DEFAULT NULL,
  \`broker_order_status\` varchar(64) DEFAULT NULL,
  \`reconciliation_state\` varchar(32) NOT NULL DEFAULT 'not_required',
  \`response_json\` json DEFAULT NULL,
  \`error_json\` json DEFAULT NULL,
  \`lifecycle_json\` json DEFAULT NULL,
  \`completed_at\` timestamp NULL DEFAULT NULL,
  \`failed_at\` timestamp NULL DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uq_order_submission_requests_user_key\` (\`user_id\`,\`idempotency_key\`),
  KEY \`idx_order_submission_requests_user_status_updated_at\` (\`user_id\`,\`status\`,\`updated_at\`),
  KEY \`idx_order_submission_requests_suggested_trade\` (\`user_id\`,\`suggested_trade_id\`,\`created_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`portfolio_snapshots\` (
  \`id\` varchar(36) NOT NULL,
  \`equity\` double NOT NULL DEFAULT '0',
  \`dayPnL\` double NOT NULL DEFAULT '0',
  \`netExposure\` varchar(100) DEFAULT NULL,
  \`diversification\` varchar(100) DEFAULT NULL,
  \`assetAllocation\` varchar(255) DEFAULT NULL,
  \`strategyMix\` varchar(255) DEFAULT NULL,
  \`riskPosture\` varchar(255) DEFAULT NULL,
  \`accountCurve\` varchar(255) DEFAULT NULL,
  \`monthlyPace\` varchar(50) DEFAULT NULL,
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`user_id\` varchar(191) NOT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`idx_portfolio_snapshots_created_at\` (\`createdAt\`),
  KEY \`idx_portfolio_snapshots_user_created_at\` (\`user_id\`,\`createdAt\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`portfolio_holdings\` (
  \`id\` varchar(36) NOT NULL,
  \`snapshotId\` varchar(36) NOT NULL,
  \`symbol\` varchar(50) NOT NULL,
  \`quantity\` double NOT NULL DEFAULT '0',
  \`marketValue\` double NOT NULL DEFAULT '0',
  \`allocationPct\` double NOT NULL DEFAULT '0',
  \`dayPnL\` double NOT NULL DEFAULT '0',
  \`unrealizedPnL\` double NOT NULL DEFAULT '0',
  \`side\` varchar(20) NOT NULL,
  \`strategy\` varchar(255) NOT NULL,
  \`riskState\` varchar(50) NOT NULL,
  \`sleeve\` varchar(50) NOT NULL,
  \`contribution\` varchar(255) DEFAULT NULL,
  \`lastRebalanceAt\` timestamp NULL DEFAULT NULL,
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`user_id\` varchar(191) NOT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`idx_portfolio_holdings_sleeve_updated_at\` (\`sleeve\`,\`updatedAt\`),
  KEY \`idx_portfolio_holdings_snapshot_symbol\` (\`snapshotId\`,\`symbol\`),
  KEY \`idx_portfolio_holdings_snapshot_user_value\` (\`snapshotId\`,\`user_id\`,\`marketValue\`),
  CONSTRAINT \`FK_d75f0c0a0ac56ec3eed53956c44\` FOREIGN KEY (\`snapshotId\`) REFERENCES \`portfolio_snapshots\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`position_read_models\` (
  \`user_id\` char(36) NOT NULL,
  \`account_id\` char(36) NOT NULL,
  \`external_id\` varchar(191) NOT NULL,
  \`broker_key\` varchar(100) NOT NULL,
  \`symbol\` varchar(100) DEFAULT NULL,
  \`side\` varchar(32) DEFAULT NULL,
  \`side_key\` varchar(32) DEFAULT NULL,
  \`side_raw\` varchar(64) DEFAULT NULL,
  \`status\` varchar(64) DEFAULT NULL,
  \`status_key\` varchar(32) DEFAULT NULL,
  \`status_raw\` varchar(64) DEFAULT NULL,
  \`status_rank\` int NOT NULL DEFAULT '0',
  \`quantity\` decimal(30,12) DEFAULT NULL,
  \`entry_price\` decimal(30,12) DEFAULT NULL,
  \`current_price\` decimal(30,12) DEFAULT NULL,
  \`closed_price\` decimal(30,12) DEFAULT NULL,
  \`unrealized_pnl\` decimal(30,12) DEFAULT NULL,
  \`realized_pnl\` decimal(30,12) DEFAULT NULL,
  \`leverage\` decimal(20,8) DEFAULT NULL,
  \`liquidation_price\` decimal(30,12) DEFAULT NULL,
  \`exposure\` decimal(30,12) DEFAULT NULL,
  \`order_price\` decimal(30,12) DEFAULT NULL,
  \`stoploss_price\` decimal(30,12) DEFAULT NULL,
  \`takeprofit_price\` decimal(30,12) DEFAULT NULL,
  \`stoploss_order_id\` varchar(191) DEFAULT NULL,
  \`takeprofit_order_id\` varchar(191) DEFAULT NULL,
  \`trigger_type\` varchar(64) DEFAULT NULL,
  \`position_created_at\` timestamp NULL DEFAULT NULL,
  \`position_updated_at\` timestamp NULL DEFAULT NULL,
  \`position_closed_at\` timestamp NULL DEFAULT NULL,
  \`first_seen_at\` timestamp NULL DEFAULT NULL,
  \`last_seen_at\` timestamp NULL DEFAULT NULL,
  \`payload_json\` json DEFAULT NULL,
  \`payload_hash\` char(64) DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`user_id\`,\`account_id\`,\`external_id\`),
  KEY \`idx_position_read_models_user_account_status_seen\` (\`user_id\`,\`account_id\`,\`status_rank\`,\`last_seen_at\`),
  KEY \`idx_position_read_models_user_broker_account_status_seen\` (\`user_id\`,\`broker_key\`,\`account_id\`,\`status_rank\`,\`last_seen_at\`),
  KEY \`idx_position_read_models_user_account_activity_at\` (\`user_id\`,\`account_id\`,\`position_updated_at\`),
  KEY \`idx_position_read_models_user_status_symbol\` (\`user_id\`,\`status_key\`,\`symbol\`),
  KEY \`idx_position_read_models_user_account_status_closed_at\` (\`user_id\`,\`account_id\`,\`status_rank\`,\`position_closed_at\`),
  KEY \`idx_position_read_models_user_broker_account_status_closed_at\` (\`user_id\`,\`broker_key\`,\`account_id\`,\`status_rank\`,\`position_closed_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`risk_account_snapshots\` (
  \`id\` char(36) NOT NULL,
  \`snapshot_id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`broker_key\` varchar(100) NOT NULL,
  \`account_id\` varchar(191) NOT NULL,
  \`account_name\` varchar(255) NOT NULL,
  \`denominator_basis\` varchar(50) DEFAULT NULL,
  \`wallet_balance\` double DEFAULT NULL,
  \`futures_balance\` double DEFAULT NULL,
  \`tracked_balance\` double DEFAULT NULL,
  \`gross_exposure\` double NOT NULL DEFAULT '0',
  \`net_exposure\` double NOT NULL DEFAULT '0',
  \`long_exposure\` double NOT NULL DEFAULT '0',
  \`short_exposure\` double NOT NULL DEFAULT '0',
  \`margin_usage_pct\` double NOT NULL DEFAULT '0',
  \`portfolio_concentration_pct\` double NOT NULL DEFAULT '0',
  \`daily_loss_usage_pct\` double NOT NULL DEFAULT '0',
  \`unrealized_pnl\` double NOT NULL DEFAULT '0',
  \`open_positions\` int unsigned NOT NULL DEFAULT '0',
  \`max_position_leverage\` double DEFAULT NULL,
  \`closest_liquidation_distance_pct\` double DEFAULT NULL,
  \`margin_usage_warn_pct\` double NOT NULL DEFAULT '0',
  \`margin_usage_critical_pct\` double NOT NULL DEFAULT '0',
  \`concentration_warn_pct\` double NOT NULL DEFAULT '0',
  \`concentration_critical_pct\` double NOT NULL DEFAULT '0',
  \`daily_loss_limit_pct\` double NOT NULL DEFAULT '0',
  \`weekly_loss_limit_pct\` double NOT NULL DEFAULT '0',
  \`monthly_loss_limit_pct\` double NOT NULL DEFAULT '0',
  \`max_leverage\` double NOT NULL DEFAULT '0',
  \`max_total_allocation\` double NOT NULL DEFAULT '0',
  \`max_avg_leverage\` double NOT NULL DEFAULT '0',
  \`funds_observed_at\` timestamp NULL DEFAULT NULL,
  \`positions_observed_at\` timestamp NULL DEFAULT NULL,
  \`orders_observed_at\` timestamp NULL DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  \`open_orders\` int unsigned NOT NULL DEFAULT '0',
  \`open_order_exposure\` double NOT NULL DEFAULT '0',
  \`reserved_order_margin\` double NOT NULL DEFAULT '0',
  PRIMARY KEY (\`id\`),
  KEY \`idx_risk_account_snapshots_snapshot_id\` (\`snapshot_id\`),
  KEY \`idx_risk_account_snapshots_user_created_at\` (\`user_id\`,\`created_at\`),
  KEY \`idx_risk_account_snapshots_user_account_created_at\` (\`user_id\`,\`account_id\`,\`created_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`risk_asset_snapshots\` (
  \`id\` char(36) NOT NULL,
  \`snapshot_id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`symbol\` varchar(100) NOT NULL,
  \`account_count\` int unsigned NOT NULL DEFAULT '0',
  \`broker_count\` int unsigned NOT NULL DEFAULT '0',
  \`position_count\` int unsigned NOT NULL DEFAULT '0',
  \`open_orders\` int unsigned NOT NULL DEFAULT '0',
  \`open_order_exposure\` double NOT NULL DEFAULT '0',
  \`reserved_order_margin\` double NOT NULL DEFAULT '0',
  \`gross_exposure\` double NOT NULL DEFAULT '0',
  \`net_exposure\` double NOT NULL DEFAULT '0',
  \`long_exposure\` double NOT NULL DEFAULT '0',
  \`short_exposure\` double NOT NULL DEFAULT '0',
  \`unrealized_pnl\` double NOT NULL DEFAULT '0',
  \`realized_pnl\` double NOT NULL DEFAULT '0',
  \`weighted_avg_leverage\` double DEFAULT NULL,
  \`max_leverage\` double DEFAULT NULL,
  \`worst_liquidation_distance_pct\` double DEFAULT NULL,
  \`risk_score\` int unsigned NOT NULL DEFAULT '0',
  \`risk_state\` varchar(20) NOT NULL DEFAULT 'ok',
  \`primary_concern\` varchar(255) DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_risk_asset_snapshots_snapshot_symbol\` (\`snapshot_id\`,\`symbol\`),
  KEY \`idx_risk_asset_snapshots_snapshot_id\` (\`snapshot_id\`),
  KEY \`idx_risk_asset_snapshots_snapshot_risk_state_score\` (\`snapshot_id\`,\`risk_state\`,\`risk_score\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`risk_broker_asset_snapshots\` (
  \`id\` char(36) NOT NULL,
  \`snapshot_id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`broker_key\` varchar(100) NOT NULL,
  \`symbol\` varchar(100) NOT NULL,
  \`policy_context_id\` char(36) DEFAULT NULL,
  \`account_count\` int unsigned NOT NULL DEFAULT '0',
  \`position_count\` int unsigned NOT NULL DEFAULT '0',
  \`open_orders\` int unsigned NOT NULL DEFAULT '0',
  \`open_order_exposure\` double NOT NULL DEFAULT '0',
  \`reserved_order_margin\` double NOT NULL DEFAULT '0',
  \`gross_exposure\` double NOT NULL DEFAULT '0',
  \`net_exposure\` double NOT NULL DEFAULT '0',
  \`long_exposure\` double NOT NULL DEFAULT '0',
  \`short_exposure\` double NOT NULL DEFAULT '0',
  \`unrealized_pnl\` double NOT NULL DEFAULT '0',
  \`realized_pnl\` double NOT NULL DEFAULT '0',
  \`weighted_avg_leverage\` double DEFAULT NULL,
  \`max_leverage\` double DEFAULT NULL,
  \`worst_liquidation_distance_pct\` double DEFAULT NULL,
  \`risk_score\` int unsigned NOT NULL DEFAULT '0',
  \`risk_state\` varchar(20) NOT NULL DEFAULT 'ok',
  \`primary_concern\` varchar(255) DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_risk_broker_asset_snapshots_snapshot_broker_symbol\` (\`snapshot_id\`,\`broker_key\`,\`symbol\`),
  KEY \`idx_risk_broker_asset_snapshots_snapshot_id\` (\`snapshot_id\`),
  KEY \`idx_risk_broker_asset_snapshots_snapshot_risk_state_score\` (\`snapshot_id\`,\`risk_state\`,\`risk_score\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`risk_broker_snapshots\` (
  \`id\` char(36) NOT NULL,
  \`snapshot_id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`broker_key\` varchar(100) NOT NULL,
  \`policy_context_id\` char(36) DEFAULT NULL,
  \`account_count\` int unsigned NOT NULL DEFAULT '0',
  \`tracked_balance\` double NOT NULL DEFAULT '0',
  \`wallet_balance\` double NOT NULL DEFAULT '0',
  \`futures_balance\` double NOT NULL DEFAULT '0',
  \`gross_exposure\` double NOT NULL DEFAULT '0',
  \`net_exposure\` double NOT NULL DEFAULT '0',
  \`long_exposure\` double NOT NULL DEFAULT '0',
  \`short_exposure\` double NOT NULL DEFAULT '0',
  \`open_positions\` int unsigned NOT NULL DEFAULT '0',
  \`open_orders\` int unsigned NOT NULL DEFAULT '0',
  \`open_order_exposure\` double NOT NULL DEFAULT '0',
  \`reserved_order_margin\` double NOT NULL DEFAULT '0',
  \`unrealized_pnl\` double NOT NULL DEFAULT '0',
  \`realized_pnl\` double NOT NULL DEFAULT '0',
  \`weighted_avg_leverage\` double DEFAULT NULL,
  \`max_leverage\` double DEFAULT NULL,
  \`worst_liquidation_distance_pct\` double DEFAULT NULL,
  \`risk_score\` int unsigned NOT NULL DEFAULT '0',
  \`risk_state\` varchar(20) NOT NULL DEFAULT 'ok',
  \`primary_concern\` varchar(255) DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_risk_broker_snapshots_snapshot_broker\` (\`snapshot_id\`,\`broker_key\`),
  KEY \`idx_risk_broker_snapshots_snapshot_id\` (\`snapshot_id\`),
  KEY \`idx_risk_broker_snapshots_snapshot_risk_state_score\` (\`snapshot_id\`,\`risk_state\`,\`risk_score\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`risk_order_snapshots\` (
  \`id\` char(36) NOT NULL,
  \`snapshot_id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`broker_key\` varchar(100) NOT NULL,
  \`account_id\` varchar(191) NOT NULL,
  \`account_name\` varchar(255) NOT NULL,
  \`external_id\` varchar(191) NOT NULL,
  \`order_id\` varchar(191) DEFAULT NULL,
  \`symbol\` varchar(100) DEFAULT NULL,
  \`side\` varchar(50) DEFAULT NULL,
  \`status\` varchar(50) DEFAULT NULL,
  \`order_type\` varchar(50) DEFAULT NULL,
  \`trigger_type\` varchar(50) DEFAULT NULL,
  \`quantity\` double DEFAULT NULL,
  \`filled_quantity\` double DEFAULT NULL,
  \`remaining_quantity\` double DEFAULT NULL,
  \`price\` double DEFAULT NULL,
  \`order_price\` double DEFAULT NULL,
  \`trigger_price\` double DEFAULT NULL,
  \`filled_price\` double DEFAULT NULL,
  \`last_price\` double DEFAULT NULL,
  \`stoploss_price\` double DEFAULT NULL,
  \`takeprofit_price\` double DEFAULT NULL,
  \`leverage\` double DEFAULT NULL,
  \`reduce_only\` tinyint(1) DEFAULT NULL,
  \`snapshot_status_rank\` int NOT NULL DEFAULT '0',
  \`notional\` double DEFAULT NULL,
  \`order_created_at\` timestamp NULL DEFAULT NULL,
  \`order_updated_at\` timestamp NULL DEFAULT NULL,
  \`order_canceled_at\` timestamp NULL DEFAULT NULL,
  \`first_seen_at\` timestamp NULL DEFAULT NULL,
  \`last_seen_at\` timestamp NULL DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  \`reserved_margin\` double DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`idx_risk_order_snapshots_snapshot_id\` (\`snapshot_id\`),
  KEY \`idx_risk_order_snapshots_user_created_at\` (\`user_id\`,\`created_at\`),
  KEY \`idx_risk_order_snapshots_user_account_created_at\` (\`user_id\`,\`account_id\`,\`created_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`risk_policies\` (
  \`id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`scope\` varchar(20) NOT NULL,
  \`broker_key\` varchar(100) DEFAULT NULL,
  \`account_id\` varchar(191) DEFAULT NULL,
  \`enabled\` tinyint(1) NOT NULL DEFAULT '1',
  \`monitor_only\` tinyint(1) NOT NULL DEFAULT '1',
  \`enforce_hard_block\` tinyint(1) NOT NULL DEFAULT '0',
  \`margin_usage_warn_pct\` double NOT NULL DEFAULT '70',
  \`margin_usage_critical_pct\` double NOT NULL DEFAULT '85',
  \`concentration_warn_pct\` double NOT NULL DEFAULT '30',
  \`concentration_critical_pct\` double NOT NULL DEFAULT '45',
  \`min_leverage\` double DEFAULT NULL,
  \`max_leverage\` double DEFAULT NULL,
  \`min_notional_per_trade\` double DEFAULT NULL,
  \`max_order_allocation\` double DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  \`daily_loss_limit_pct\` double NOT NULL DEFAULT '5',
  \`weekly_loss_limit_pct\` double NOT NULL DEFAULT '12',
  \`monthly_loss_limit_pct\` double NOT NULL DEFAULT '20',
  \`max_total_allocation\` double DEFAULT NULL,
  \`max_avg_leverage\` double DEFAULT NULL,
  \`normalized_target_key\` varchar(255) GENERATED ALWAYS AS ((case when (\`scope\` = _utf8mb4'user') then _utf8mb4'__user__' when (\`scope\` = _utf8mb4'broker') then concat(_utf8mb4'broker::',lower(trim(coalesce(\`broker_key\`,_utf8mb4'')))) else concat(_utf8mb4'__invalid__::',lower(trim(coalesce(\`scope\`,_utf8mb4'')))) end)) STORED,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_risk_policies_user_target_key\` (\`user_id\`,\`normalized_target_key\`),
  KEY \`idx_risk_policies_user_scope\` (\`user_id\`,\`scope\`),
  KEY \`idx_risk_policies_user_broker\` (\`user_id\`,\`broker_key\`),
  KEY \`idx_risk_policies_user_account\` (\`user_id\`,\`account_id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`risk_policy_versions\` (
  \`id\` char(36) NOT NULL,
  \`policy_id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`actor_user_id\` varchar(191) NOT NULL,
  \`version_payload\` text NOT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  KEY \`idx_risk_policy_versions_policy_created\` (\`policy_id\`,\`created_at\`),
  KEY \`idx_risk_policy_versions_user_created\` (\`user_id\`,\`created_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`risk_position_snapshots\` (
  \`id\` char(36) NOT NULL,
  \`snapshot_id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`broker_key\` varchar(100) NOT NULL,
  \`account_id\` varchar(191) NOT NULL,
  \`account_name\` varchar(255) NOT NULL,
  \`position_id\` varchar(191) NOT NULL,
  \`symbol\` varchar(100) NOT NULL,
  \`side\` varchar(50) DEFAULT NULL,
  \`side_key\` varchar(20) DEFAULT NULL,
  \`status\` varchar(50) DEFAULT NULL,
  \`status_key\` varchar(20) DEFAULT NULL,
  \`quantity\` double DEFAULT NULL,
  \`entry_price\` double DEFAULT NULL,
  \`current_price\` double DEFAULT NULL,
  \`exposure\` double NOT NULL DEFAULT '0',
  \`unrealized_pnl\` double DEFAULT NULL,
  \`realized_pnl\` double DEFAULT NULL,
  \`leverage\` double DEFAULT NULL,
  \`liquidation_price\` double DEFAULT NULL,
  \`liquidation_distance_pct\` double DEFAULT NULL,
  \`concentration_pct\` double DEFAULT NULL,
  \`risk_state\` varchar(20) NOT NULL DEFAULT 'ok',
  \`risk_notes_json\` json DEFAULT NULL,
  \`position_opened_at\` timestamp NULL DEFAULT NULL,
  \`source_updated_at\` timestamp NULL DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  KEY \`idx_risk_position_snapshots_snapshot_id\` (\`snapshot_id\`),
  KEY \`idx_risk_position_snapshots_user_created_at\` (\`user_id\`,\`created_at\`),
  KEY \`idx_risk_position_snapshots_user_account_created_at\` (\`user_id\`,\`account_id\`,\`created_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`risk_request_checks\` (
  \`id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`snapshot_id\` char(36) DEFAULT NULL,
  \`suggested_trade_id\` char(36) DEFAULT NULL,
  \`automation_id\` char(36) DEFAULT NULL,
  \`automation_run_id\` char(36) DEFAULT NULL,
  \`source_type\` varchar(40) NOT NULL,
  \`execution_mode\` varchar(20) NOT NULL,
  \`approval_mode\` varchar(20) NOT NULL,
  \`route_mode\` varchar(40) NOT NULL,
  \`broker_key\` varchar(100) DEFAULT NULL,
  \`account_id\` varchar(191) DEFAULT NULL,
  \`symbol\` varchar(64) NOT NULL,
  \`timeframe\` varchar(16) DEFAULT NULL,
  \`side\` varchar(10) NOT NULL,
  \`order_type\` varchar(20) NOT NULL,
  \`time_in_force\` varchar(10) DEFAULT NULL,
  \`quantity_mode\` varchar(20) NOT NULL,
  \`quantity\` double DEFAULT NULL,
  \`notional\` double DEFAULT NULL,
  \`risk_percent\` double DEFAULT NULL,
  \`entry_price\` double DEFAULT NULL,
  \`stop_loss_price\` double DEFAULT NULL,
  \`take_profit_targets_json\` json DEFAULT NULL,
  \`leverage\` double DEFAULT NULL,
  \`reduce_only\` tinyint(1) NOT NULL DEFAULT '0',
  \`status\` varchar(20) NOT NULL,
  \`freshness_state\` varchar(20) NOT NULL,
  \`snapshot_lag_minutes\` double DEFAULT NULL,
  \`checked_at\` timestamp NOT NULL,
  \`expires_at\` timestamp NULL DEFAULT NULL,
  \`allowed\` tinyint(1) NOT NULL DEFAULT '0',
  \`blocked\` tinyint(1) NOT NULL DEFAULT '0',
  \`approval_required\` tinyint(1) NOT NULL DEFAULT '0',
  \`blocking_rule_count\` int unsigned NOT NULL DEFAULT '0',
  \`warning_rule_count\` int unsigned NOT NULL DEFAULT '0',
  \`summary\` text NOT NULL,
  \`gross_exposure_delta\` double DEFAULT NULL,
  \`net_exposure_delta\` double DEFAULT NULL,
  \`open_order_exposure_delta\` double DEFAULT NULL,
  \`reserved_order_margin_delta\` double DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  KEY \`idx_risk_request_checks_user_created_at\` (\`user_id\`,\`created_at\`),
  KEY \`idx_risk_request_checks_user_snapshot_created_at\` (\`user_id\`,\`snapshot_id\`,\`created_at\`),
  KEY \`idx_risk_request_checks_user_suggested_trade_created_at\` (\`user_id\`,\`suggested_trade_id\`,\`created_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`risk_request_rule_evaluations\` (
  \`id\` char(36) NOT NULL,
  \`check_id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`snapshot_id\` char(36) DEFAULT NULL,
  \`policy_context_id\` char(36) DEFAULT NULL,
  \`scope_type\` varchar(40) NOT NULL,
  \`scope_key\` varchar(191) NOT NULL,
  \`scope_label\` varchar(255) DEFAULT NULL,
  \`broker_key\` varchar(100) DEFAULT NULL,
  \`account_id\` varchar(191) DEFAULT NULL,
  \`symbol\` varchar(64) DEFAULT NULL,
  \`rule_code\` varchar(120) NOT NULL,
  \`metric_name\` varchar(120) DEFAULT NULL,
  \`actual_value\` double DEFAULT NULL,
  \`basis_value\` double DEFAULT NULL,
  \`warn_threshold_value\` double DEFAULT NULL,
  \`critical_threshold_value\` double DEFAULT NULL,
  \`status\` varchar(20) NOT NULL,
  \`blocking\` tinyint(1) NOT NULL DEFAULT '0',
  \`message\` text NOT NULL,
  \`sort_order\` int unsigned NOT NULL DEFAULT '0',
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  KEY \`idx_risk_request_rule_evaluations_check_id\` (\`check_id\`),
  KEY \`idx_risk_request_rule_evaluations_check_scope\` (\`check_id\`,\`scope_type\`,\`scope_key\`),
  KEY \`idx_risk_request_rule_evaluations_check_status\` (\`check_id\`,\`status\`,\`blocking\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`risk_request_scope_impacts\` (
  \`id\` char(36) NOT NULL,
  \`check_id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`snapshot_id\` char(36) DEFAULT NULL,
  \`scope_type\` varchar(40) NOT NULL,
  \`scope_key\` varchar(191) NOT NULL,
  \`scope_label\` varchar(255) DEFAULT NULL,
  \`broker_key\` varchar(100) DEFAULT NULL,
  \`account_id\` varchar(191) DEFAULT NULL,
  \`symbol\` varchar(64) DEFAULT NULL,
  \`before_gross_exposure\` double DEFAULT NULL,
  \`before_net_exposure\` double DEFAULT NULL,
  \`before_open_order_exposure\` double DEFAULT NULL,
  \`before_reserved_order_margin\` double DEFAULT NULL,
  \`before_margin_usage_pct\` double DEFAULT NULL,
  \`before_allocation_pct\` double DEFAULT NULL,
  \`before_risk_score\` double DEFAULT NULL,
  \`before_risk_state\` varchar(20) DEFAULT NULL,
  \`delta_gross_exposure\` double DEFAULT NULL,
  \`delta_net_exposure\` double DEFAULT NULL,
  \`delta_open_order_exposure\` double DEFAULT NULL,
  \`delta_reserved_order_margin\` double DEFAULT NULL,
  \`after_gross_exposure\` double DEFAULT NULL,
  \`after_net_exposure\` double DEFAULT NULL,
  \`after_open_order_exposure\` double DEFAULT NULL,
  \`after_reserved_order_margin\` double DEFAULT NULL,
  \`after_margin_usage_pct\` double DEFAULT NULL,
  \`after_allocation_pct\` double DEFAULT NULL,
  \`after_risk_score\` double DEFAULT NULL,
  \`after_risk_state\` varchar(20) DEFAULT NULL,
  \`sort_order\` int unsigned NOT NULL DEFAULT '0',
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  KEY \`idx_risk_request_scope_impacts_check_id\` (\`check_id\`),
  KEY \`idx_risk_request_scope_impacts_check_scope\` (\`check_id\`,\`scope_type\`,\`scope_key\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`risk_rule_evaluations\` (
  \`id\` char(36) NOT NULL,
  \`snapshot_id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`policy_context_id\` char(36) DEFAULT NULL,
  \`source_type\` varchar(40) NOT NULL,
  \`scope_type\` varchar(40) NOT NULL,
  \`scope_key\` varchar(191) NOT NULL,
  \`scope_label\` varchar(255) DEFAULT NULL,
  \`broker_key\` varchar(100) DEFAULT NULL,
  \`account_id\` varchar(191) DEFAULT NULL,
  \`position_id\` varchar(191) DEFAULT NULL,
  \`symbol\` varchar(100) DEFAULT NULL,
  \`rule_code\` varchar(120) NOT NULL,
  \`metric_name\` varchar(120) DEFAULT NULL,
  \`actual_value\` double DEFAULT NULL,
  \`basis_value\` double DEFAULT NULL,
  \`warn_threshold_value\` double DEFAULT NULL,
  \`critical_threshold_value\` double DEFAULT NULL,
  \`status\` varchar(20) NOT NULL,
  \`bucket\` varchar(255) DEFAULT NULL,
  \`exposure\` varchar(120) DEFAULT NULL,
  \`threshold\` varchar(255) DEFAULT NULL,
  \`action\` text,
  \`alert_severity\` varchar(20) DEFAULT NULL,
  \`alert_message\` text,
  \`alert_symbol\` varchar(100) DEFAULT NULL,
  \`alert_channel\` varchar(100) DEFAULT NULL,
  \`alert_status\` varchar(40) DEFAULT NULL,
  \`sort_order\` int unsigned NOT NULL DEFAULT '0',
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  KEY \`idx_risk_rule_evaluations_snapshot_id\` (\`snapshot_id\`),
  KEY \`idx_risk_rule_evaluations_snapshot_scope\` (\`snapshot_id\`,\`scope_type\`,\`scope_key\`),
  KEY \`idx_risk_rule_evaluations_user_source_created_at\` (\`user_id\`,\`source_type\`,\`created_at\`),
  KEY \`idx_risk_rule_evaluations_snapshot_alert_severity\` (\`snapshot_id\`,\`alert_severity\`,\`created_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`risk_snapshot_policy_contexts\` (
  \`id\` char(36) NOT NULL,
  \`snapshot_id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`context_key\` varchar(191) NOT NULL,
  \`policy_id\` char(36) DEFAULT NULL,
  \`policy_scope\` varchar(20) NOT NULL,
  \`policy_target_key\` varchar(191) NOT NULL,
  \`enabled\` tinyint(1) NOT NULL DEFAULT '1',
  \`monitor_only\` tinyint(1) NOT NULL DEFAULT '1',
  \`enforce_hard_block\` tinyint(1) NOT NULL DEFAULT '0',
  \`margin_usage_warn_pct\` double NOT NULL DEFAULT '70',
  \`margin_usage_critical_pct\` double NOT NULL DEFAULT '85',
  \`concentration_warn_pct\` double NOT NULL DEFAULT '30',
  \`concentration_critical_pct\` double NOT NULL DEFAULT '45',
  \`daily_loss_limit_pct\` double NOT NULL DEFAULT '5',
  \`weekly_loss_limit_pct\` double NOT NULL DEFAULT '12',
  \`monthly_loss_limit_pct\` double NOT NULL DEFAULT '20',
  \`min_leverage\` double DEFAULT NULL,
  \`max_leverage\` double DEFAULT NULL,
  \`min_notional_per_trade\` double DEFAULT NULL,
  \`max_order_allocation\` double DEFAULT NULL,
  \`max_total_allocation\` double DEFAULT NULL,
  \`max_avg_leverage\` double DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_risk_snapshot_policy_contexts_snapshot_context_key\` (\`snapshot_id\`,\`context_key\`),
  KEY \`idx_risk_snapshot_policy_contexts_snapshot_id\` (\`snapshot_id\`),
  KEY \`idx_risk_snapshot_policy_contexts_user_scope_created_at\` (\`user_id\`,\`policy_scope\`,\`created_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`risk_snapshot_source_coverage\` (
  \`id\` char(36) NOT NULL,
  \`snapshot_id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`broker_key\` varchar(100) NOT NULL,
  \`account_id\` varchar(191) NOT NULL,
  \`account_name\` varchar(255) NOT NULL,
  \`latest_funds_snapshot_id\` char(36) DEFAULT NULL,
  \`latest_funds_snapshot_date\` varchar(64) DEFAULT NULL,
  \`latest_funds_observed_at\` timestamp NULL DEFAULT NULL,
  \`latest_funds_computed_at\` timestamp NULL DEFAULT NULL,
  \`latest_funds_last_attempt_at\` timestamp NULL DEFAULT NULL,
  \`latest_funds_fetch_status\` varchar(20) DEFAULT NULL,
  \`latest_funds_error_message\` text,
  \`latest_funds_source\` varchar(50) DEFAULT NULL,
  \`latest_wallet_available\` tinyint(1) NOT NULL DEFAULT '0',
  \`latest_futures_available\` tinyint(1) NOT NULL DEFAULT '0',
  \`latest_success_funds_snapshot_id\` char(36) DEFAULT NULL,
  \`latest_success_funds_snapshot_date\` varchar(64) DEFAULT NULL,
  \`latest_success_funds_observed_at\` timestamp NULL DEFAULT NULL,
  \`latest_success_funds_computed_at\` timestamp NULL DEFAULT NULL,
  \`latest_success_funds_source\` varchar(50) DEFAULT NULL,
  \`latest_success_wallet_available\` tinyint(1) NOT NULL DEFAULT '0',
  \`latest_success_futures_available\` tinyint(1) NOT NULL DEFAULT '0',
  \`positions_observed_at\` timestamp NULL DEFAULT NULL,
  \`positions_checkpoint_at\` timestamp NULL DEFAULT NULL,
  \`open_positions\` int unsigned NOT NULL DEFAULT '0',
  \`position_total_rows\` int unsigned NOT NULL DEFAULT '0',
  \`position_snapshot_rows\` int unsigned NOT NULL DEFAULT '0',
  \`position_read_model_rows\` int unsigned NOT NULL DEFAULT '0',
  \`rows_missing_from_read_model\` int unsigned NOT NULL DEFAULT '0',
  \`rows_behind_snapshot\` int unsigned NOT NULL DEFAULT '0',
  \`orphan_read_model_rows\` int unsigned NOT NULL DEFAULT '0',
  \`latest_position_snapshot_seen_at\` timestamp NULL DEFAULT NULL,
  \`latest_position_read_model_seen_at\` timestamp NULL DEFAULT NULL,
  \`open_order_rows\` int unsigned NOT NULL DEFAULT '0',
  \`latest_order_seen_at\` timestamp NULL DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_risk_snapshot_source_coverage_snapshot_account\` (\`snapshot_id\`,\`account_id\`),
  KEY \`idx_risk_snapshot_source_coverage_snapshot_id\` (\`snapshot_id\`),
  KEY \`idx_risk_snapshot_source_coverage_user_account_created_at\` (\`user_id\`,\`account_id\`,\`created_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`risk_snapshots\` (
  \`id\` varchar(36) NOT NULL,
  \`portfolioRisk\` varchar(50) DEFAULT NULL,
  \`breachedRules\` int unsigned NOT NULL DEFAULT '0',
  \`liquidationWatch\` int unsigned NOT NULL DEFAULT '0',
  \`capitalAtRisk\` double NOT NULL DEFAULT '0',
  \`marginUsage\` varchar(50) DEFAULT NULL,
  \`drawdownBudgetUsed\` varchar(50) DEFAULT NULL,
  \`atRiskPositions\` int unsigned NOT NULL DEFAULT '0',
  \`ruleViolations\` int unsigned NOT NULL DEFAULT '0',
  \`portfolioRiskScore\` varchar(50) DEFAULT NULL,
  \`primaryConcern\` varchar(255) DEFAULT NULL,
  \`riskByPosition\` varchar(255) DEFAULT NULL,
  \`riskByStrategy\` varchar(255) DEFAULT NULL,
  \`riskByGuardrail\` varchar(255) DEFAULT NULL,
  \`guardrailOne\` varchar(255) DEFAULT NULL,
  \`guardrailTwo\` varchar(255) DEFAULT NULL,
  \`guardrailThree\` varchar(255) DEFAULT NULL,
  \`actionOne\` varchar(255) DEFAULT NULL,
  \`actionTwo\` varchar(255) DEFAULT NULL,
  \`actionThree\` varchar(255) DEFAULT NULL,
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`user_id\` varchar(191) NOT NULL,
  \`weeklyDrawdownBudgetUsed\` varchar(50) DEFAULT NULL,
  \`monthlyDrawdownBudgetUsed\` varchar(50) DEFAULT NULL,
  \`denominator_basis\` varchar(50) DEFAULT NULL,
  \`portfolio_equity\` double NOT NULL DEFAULT '0',
  \`gross_exposure\` double NOT NULL DEFAULT '0',
  \`net_exposure\` double NOT NULL DEFAULT '0',
  \`long_exposure\` double NOT NULL DEFAULT '0',
  \`short_exposure\` double NOT NULL DEFAULT '0',
  \`funds_observed_at\` timestamp NULL DEFAULT NULL,
  \`positions_observed_at\` timestamp NULL DEFAULT NULL,
  \`orders_observed_at\` timestamp NULL DEFAULT NULL,
  \`open_orders\` int unsigned NOT NULL DEFAULT '0',
  \`open_order_exposure\` double NOT NULL DEFAULT '0',
  \`reserved_order_margin\` double NOT NULL DEFAULT '0',
  PRIMARY KEY (\`id\`),
  KEY \`idx_risk_snapshots_created_at\` (\`createdAt\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`scheduler_commands\` (
  \`id\` char(36) NOT NULL,
  \`scheduler_key\` varchar(100) NOT NULL,
  \`command_type\` varchar(50) NOT NULL,
  \`actor_user_id\` varchar(191) DEFAULT NULL,
  \`initiated_by_type\` varchar(32) DEFAULT NULL,
  \`initiated_by_user_id\` varchar(191) DEFAULT NULL,
  \`initiated_by_label\` varchar(191) DEFAULT NULL,
  \`execution_context\` varchar(32) DEFAULT NULL,
  \`payload_json\` text,
  \`status\` varchar(30) NOT NULL DEFAULT 'Pending',
  \`processed_at\` timestamp NULL DEFAULT NULL,
  \`error_message\` text,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  \`worker_id\` varchar(191) DEFAULT NULL,
  \`claimed_at\` timestamp NULL DEFAULT NULL,
  \`repaired_at\` timestamp NULL DEFAULT NULL,
  \`repair_reason\` text,
  PRIMARY KEY (\`id\`),
  KEY \`idx_scheduler_commands_status_created_at\` (\`status\`,\`created_at\`),
  KEY \`idx_scheduler_commands_scheduler_key_status\` (\`scheduler_key\`,\`status\`),
  KEY \`idx_scheduler_commands_scheduler_actor_status\` (\`scheduler_key\`,\`actor_user_id\`,\`status\`,\`created_at\`),
  KEY \`idx_scheduler_commands_status_claimed_at\` (\`status\`,\`claimed_at\`),
  KEY \`idx_scheduler_commands_worker_status_claimed_at\` (\`worker_id\`,\`status\`,\`claimed_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`scheduler_configs\` (
  \`id\` char(36) NOT NULL,
  \`key\` varchar(100) NOT NULL,
  \`name\` varchar(191) NOT NULL,
  \`description\` varchar(255) DEFAULT NULL,
  \`enabled\` tinyint(1) NOT NULL DEFAULT '0',
  \`cron_expression\` varchar(64) NOT NULL,
  \`timezone\` varchar(64) NOT NULL DEFAULT 'Asia/Kolkata',
  \`run_at\` varchar(5) NOT NULL DEFAULT '01:00',
  \`interval_days\` int NOT NULL DEFAULT '1',
  \`batch_size\` int NOT NULL DEFAULT '200',
  \`scheduler_type\` varchar(16) NOT NULL DEFAULT 'global',
  \`config\` text,
  \`last_started_at\` timestamp NULL DEFAULT NULL,
  \`last_finished_at\` timestamp NULL DEFAULT NULL,
  \`last_status\` varchar(32) DEFAULT NULL,
  \`last_error\` text,
  \`running_lock_until\` timestamp NULL DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_scheduler_configs_key\` (\`key\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`scheduler_orders_snapshots\` (
  \`id\` char(36) NOT NULL,
  \`user_id\` char(36) NOT NULL,
  \`account_id\` char(36) NOT NULL,
  \`broker_key\` varchar(100) NOT NULL,
  \`external_id\` varchar(191) NOT NULL,
  \`symbol\` varchar(100) DEFAULT NULL,
  \`order_status\` varchar(64) DEFAULT NULL,
  \`status_rank\` int NOT NULL DEFAULT '0',
  \`payload_json\` json DEFAULT NULL,
  \`payload_hash\` char(64) DEFAULT NULL,
  \`first_seen_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`last_seen_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_scheduler_orders_snapshot\` (\`user_id\`,\`account_id\`,\`external_id\`),
  KEY \`idx_scheduler_orders_last_seen\` (\`last_seen_at\`),
  KEY \`idx_scheduler_orders_user_account\` (\`user_id\`,\`account_id\`),
  KEY \`idx_scheduler_orders_user_account_status_seen\` (\`user_id\`,\`account_id\`,\`status_rank\`,\`last_seen_at\`),
  KEY \`idx_scheduler_orders_user_account_status_updated\` (\`user_id\`,\`account_id\`,\`status_rank\`,\`updated_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`scheduler_positions_snapshots\` (
  \`id\` char(36) NOT NULL,
  \`user_id\` char(36) NOT NULL,
  \`account_id\` char(36) NOT NULL,
  \`broker_key\` varchar(100) NOT NULL,
  \`external_id\` varchar(191) NOT NULL,
  \`symbol\` varchar(100) DEFAULT NULL,
  \`status\` varchar(64) DEFAULT NULL,
  \`status_rank\` int NOT NULL DEFAULT '0',
  \`payload_json\` json DEFAULT NULL,
  \`payload_hash\` char(64) DEFAULT NULL,
  \`first_seen_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`last_seen_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_scheduler_positions_snapshot\` (\`user_id\`,\`account_id\`,\`external_id\`),
  KEY \`idx_scheduler_positions_last_seen\` (\`last_seen_at\`),
  KEY \`idx_scheduler_positions_user_account\` (\`user_id\`,\`account_id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`scheduler_run_locks\` (
  \`scope_key\` varchar(255) NOT NULL,
  \`lock_until\` timestamp NULL DEFAULT NULL,
  \`run_id\` char(36) DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`scope_key\`),
  KEY \`idx_scheduler_run_locks_lock_until\` (\`lock_until\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`scheduler_run_logs\` (
  \`id\` char(36) NOT NULL,
  \`scheduler_key\` varchar(100) NOT NULL,
  \`status\` varchar(32) NOT NULL,
  \`actor_user_id\` varchar(191) DEFAULT NULL,
  \`initiated_by_type\` varchar(32) DEFAULT NULL,
  \`initiated_by_user_id\` varchar(191) DEFAULT NULL,
  \`initiated_by_label\` varchar(191) DEFAULT NULL,
  \`execution_context\` varchar(32) DEFAULT NULL,
  \`started_at\` timestamp NOT NULL,
  \`finished_at\` timestamp NULL DEFAULT NULL,
  \`duration_ms\` int DEFAULT NULL,
  \`processed_accounts\` int NOT NULL DEFAULT '0',
  \`inserted_assets\` int NOT NULL DEFAULT '0',
  \`updated_assets\` int NOT NULL DEFAULT '0',
  \`skipped_assets\` int NOT NULL DEFAULT '0',
  \`error_message\` text,
  \`meta_json\` text,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`command_id\` char(36) DEFAULT NULL,
  \`worker_id\` varchar(191) DEFAULT NULL,
  \`last_progress_at\` timestamp NULL DEFAULT NULL,
  \`repaired_at\` timestamp NULL DEFAULT NULL,
  \`repair_reason\` text,
  PRIMARY KEY (\`id\`),
  KEY \`idx_scheduler_run_logs_key_started\` (\`scheduler_key\`,\`started_at\`),
  KEY \`idx_scheduler_run_logs_scheduler_actor_started\` (\`scheduler_key\`,\`actor_user_id\`,\`started_at\`),
  KEY \`idx_scheduler_run_logs_command_id\` (\`command_id\`),
  KEY \`idx_scheduler_run_logs_status_last_progress_at\` (\`status\`,\`last_progress_at\`),
  KEY \`idx_scheduler_run_logs_worker_status_started_at\` (\`worker_id\`,\`status\`,\`started_at\`),
  CONSTRAINT \`fk_scheduler_run_logs_command_id\` FOREIGN KEY (\`command_id\`) REFERENCES \`scheduler_commands\` (\`id\`) ON DELETE SET NULL,
  CONSTRAINT \`fk_scheduler_run_logs_scheduler_key\` FOREIGN KEY (\`scheduler_key\`) REFERENCES \`scheduler_configs\` (\`key\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`exchange_asset_update_logs\` (
  \`id\` char(36) NOT NULL,
  \`run_log_id\` char(36) NOT NULL,
  \`initiated_by_type\` varchar(32) DEFAULT NULL,
  \`initiated_by_user_id\` varchar(191) DEFAULT NULL,
  \`initiated_by_label\` varchar(191) DEFAULT NULL,
  \`execution_context\` varchar(32) DEFAULT NULL,
  \`source\` varchar(64) NOT NULL,
  \`account_id\` char(36) DEFAULT NULL,
  \`connection_id\` char(36) DEFAULT NULL,
  \`action_type\` varchar(32) NOT NULL,
  \`symbol\` varchar(100) DEFAULT NULL,
  \`external_id\` varchar(255) DEFAULT NULL,
  \`asset_id\` varchar(36) DEFAULT NULL,
  \`message\` varchar(255) DEFAULT NULL,
  \`detail_json\` text,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  KEY \`idx_exchange_asset_update_logs_run_created\` (\`run_log_id\`,\`created_at\`),
  KEY \`idx_exchange_asset_update_logs_source_symbol\` (\`source\`,\`symbol\`),
  KEY \`idx_exchange_asset_update_logs_created_at\` (\`created_at\`),
  CONSTRAINT \`fk_exchange_asset_update_logs_run_log\` FOREIGN KEY (\`run_log_id\`) REFERENCES \`scheduler_run_logs\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`scheduler_health_check_results\` (
  \`id\` char(36) NOT NULL,
  \`run_log_id\` char(36) NOT NULL,
  \`check_id\` varchar(100) NOT NULL,
  \`check_label\` varchar(191) NOT NULL,
  \`status\` varchar(32) NOT NULL,
  \`detail\` text,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  KEY \`idx_scheduler_health_check_results_run_created\` (\`run_log_id\`,\`created_at\`),
  KEY \`idx_scheduler_health_check_results_status_created\` (\`status\`,\`created_at\`),
  CONSTRAINT \`fk_scheduler_health_check_results_run_log\` FOREIGN KEY (\`run_log_id\`) REFERENCES \`scheduler_run_logs\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`scheduler_sync_checkpoints\` (
  \`scheduler_key\` varchar(64) NOT NULL,
  \`account_id\` char(36) NOT NULL,
  \`checkpoint_at\` datetime NOT NULL,
  \`updated_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`scheduler_key\`,\`account_id\`),
  UNIQUE KEY \`uidx_sync_checkpoint\` (\`scheduler_key\`,\`account_id\`),
  KEY \`idx_scheduler_sync_checkpoints_checkpoint_at\` (\`checkpoint_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`scheduler_sync_pending_records\` (
  \`id\` char(36) NOT NULL,
  \`scheduler_key\` varchar(64) NOT NULL,
  \`account_id\` char(36) NOT NULL,
  \`record_key\` varchar(191) NOT NULL,
  \`status\` varchar(16) NOT NULL DEFAULT 'pending',
  \`retry_count\` int NOT NULL DEFAULT '0',
  \`last_error\` varchar(500) DEFAULT NULL,
  \`next_retry_at\` datetime DEFAULT NULL,
  \`created_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uniq_scheduler_sync_pending_record\` (\`scheduler_key\`,\`account_id\`,\`record_key\`),
  KEY \`idx_scheduler_sync_pending_status\` (\`scheduler_key\`,\`account_id\`,\`status\`,\`next_retry_at\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`settings_audit_logs\` (
  \`id\` varchar(36) NOT NULL,
  \`fieldName\` varchar(50) NOT NULL,
  \`oldValue\` text,
  \`newValue\` text,
  \`actor\` varchar(100) DEFAULT NULL,
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`user_id\` char(36) NOT NULL,
  \`oldValueType\` varchar(16) DEFAULT NULL,
  \`oldValueJson\` json DEFAULT NULL,
  \`newValueType\` varchar(16) DEFAULT NULL,
  \`newValueJson\` json DEFAULT NULL,
  \`changeType\` varchar(16) DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`idx_settings_audit_logs_user_created_at\` (\`user_id\`,\`createdAt\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`signals\` (
  \`id\` varchar(36) NOT NULL,
  \`symbol\` varchar(50) NOT NULL,
  \`source\` varchar(100) NOT NULL,
  \`confidence\` double NOT NULL,
  \`direction\` varchar(20) DEFAULT NULL,
  \`timeframe\` varchar(20) DEFAULT NULL,
  \`status\` varchar(30) NOT NULL,
  \`regime\` varchar(50) DEFAULT NULL,
  \`aiScore\` int unsigned DEFAULT NULL,
  \`thesis\` text,
  \`route\` varchar(50) DEFAULT NULL,
  \`riskNote\` text,
  \`promotionState\` varchar(30) DEFAULT NULL,
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`dedupeKey\` varchar(191) DEFAULT NULL,
  \`market\` varchar(30) DEFAULT NULL,
  \`signalTime\` datetime DEFAULT NULL,
  \`entryPrice\` decimal(30,12) DEFAULT NULL,
  \`sourceRefType\` varchar(40) DEFAULT NULL,
  \`sourceRefId\` varchar(191) DEFAULT NULL,
  \`expiresAt\` datetime DEFAULT NULL,
  \`metadata\` json DEFAULT NULL,
  \`user_id\` varchar(191) DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`ux_signals_dedupe_key\` (\`dedupeKey\`),
  KEY \`idx_signals_symbol_created_at\` (\`symbol\`,\`createdAt\`),
  KEY \`idx_signals_status_created_at\` (\`status\`,\`createdAt\`),
  KEY \`idx_signals_source_ref_signal_time\` (\`sourceRefType\`,\`sourceRefId\`,\`signalTime\`),
  KEY \`idx_signals_user_status_signal_time\` (\`user_id\`,\`status\`,\`signalTime\`),
  KEY \`idx_signals_user_symbol_created_at\` (\`user_id\`,\`symbol\`,\`createdAt\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`signal_actions\` (
  \`id\` varchar(36) NOT NULL,
  \`signalId\` varchar(36) NOT NULL,
  \`actionType\` varchar(30) NOT NULL,
  \`target\` varchar(50) DEFAULT NULL,
  \`note\` text,
  \`actor\` varchar(100) DEFAULT NULL,
  \`metadata\` json DEFAULT NULL,
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  KEY \`idx_signal_actions_signal_created_at\` (\`signalId\`,\`createdAt\`),
  CONSTRAINT \`FK_92c51783eaec8a38da9b1a06c5a\` FOREIGN KEY (\`signalId\`) REFERENCES \`signals\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`signal_alert_links\` (
  \`id\` char(36) NOT NULL,
  \`signal_id\` char(36) NOT NULL,
  \`alert_id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`relation_type\` varchar(30) NOT NULL DEFAULT 'related',
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`ux_signal_alert_links_signal_alert_relation\` (\`signal_id\`,\`alert_id\`,\`relation_type\`),
  KEY \`idx_signal_alert_links_signal_created_at\` (\`signal_id\`,\`created_at\`),
  KEY \`idx_signal_alert_links_alert_created_at\` (\`alert_id\`,\`created_at\`),
  KEY \`idx_signal_alert_links_user_signal_created_at\` (\`user_id\`,\`signal_id\`,\`created_at\`),
  CONSTRAINT \`fk_signal_alert_links_alert_id\` FOREIGN KEY (\`alert_id\`) REFERENCES \`alerts\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`fk_signal_alert_links_signal_id\` FOREIGN KEY (\`signal_id\`) REFERENCES \`signals\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`suggested_trades\` (
  \`id\` char(36) NOT NULL,
  \`automation_id\` char(36) NOT NULL,
  \`automation_run_id\` char(36) NOT NULL,
  \`user_id\` char(36) NOT NULL,
  \`source_backtest_id\` char(36) DEFAULT NULL,
  \`source_template_id\` char(36) DEFAULT NULL,
  \`source_setup_key\` varchar(191) DEFAULT NULL,
  \`symbol\` varchar(64) NOT NULL,
  \`timeframe\` varchar(16) NOT NULL,
  \`side\` varchar(10) NOT NULL,
  \`signal_time\` timestamp NOT NULL,
  \`status\` varchar(32) NOT NULL DEFAULT 'Open',
  \`confidence\` double DEFAULT NULL,
  \`score\` double DEFAULT NULL,
  \`entry_price\` decimal(30,12) DEFAULT NULL,
  \`stop_loss_price\` decimal(30,12) DEFAULT NULL,
  \`take_profit_targets\` json DEFAULT NULL,
  \`entry_rule\` text,
  \`exit_rule\` text,
  \`rationale\` text,
  \`dedupe_key\` varchar(191) NOT NULL,
  \`meta_json\` json DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_suggested_trades_automation_dedupe_key\` (\`automation_id\`,\`dedupe_key\`),
  KEY \`idx_suggested_trades_automation_signal_time\` (\`automation_id\`,\`signal_time\`),
  KEY \`idx_suggested_trades_user_status_signal_time\` (\`user_id\`,\`status\`,\`signal_time\`),
  KEY \`idx_suggested_trades_symbol_timeframe_status\` (\`symbol\`,\`timeframe\`,\`status\`),
  KEY \`idx_suggested_trades_user_automation_status_signal_time\` (\`user_id\`,\`automation_id\`,\`status\`,\`signal_time\`),
  KEY \`idx_suggested_trades_user_run_signal_time\` (\`user_id\`,\`automation_run_id\`,\`signal_time\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`automation_run_outputs\` (
  \`id\` char(36) NOT NULL,
  \`automation_id\` char(36) NOT NULL,
  \`automation_run_id\` char(36) NOT NULL,
  \`user_id\` char(36) NOT NULL,
  \`suggested_trade_id\` char(36) DEFAULT NULL,
  \`output_type\` varchar(64) NOT NULL,
  \`status\` varchar(32) NOT NULL DEFAULT 'Created',
  \`title\` varchar(255) DEFAULT NULL,
  \`dedupe_key\` varchar(191) DEFAULT NULL,
  \`payload_json\` json DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_automation_run_outputs_run_type_dedupe\` (\`automation_run_id\`,\`output_type\`,\`dedupe_key\`),
  KEY \`idx_automation_run_outputs_run_created_at\` (\`automation_run_id\`,\`created_at\`),
  KEY \`idx_automation_run_outputs_type_status\` (\`output_type\`,\`status\`),
  KEY \`idx_automation_run_outputs_user_created_at\` (\`user_id\`,\`created_at\`),
  KEY \`idx_automation_run_outputs_suggested_trade_id\` (\`suggested_trade_id\`),
  CONSTRAINT \`fk_automation_run_outputs_suggested_trade\` FOREIGN KEY (\`suggested_trade_id\`) REFERENCES \`suggested_trades\` (\`id\`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`paper_orders\` (
  \`id\` char(36) NOT NULL,
  \`user_id\` char(36) NOT NULL,
  \`suggested_trade_id\` char(36) DEFAULT NULL,
  \`asset_id\` varchar(191) NOT NULL,
  \`broker_key\` varchar(100) NOT NULL,
  \`account_id\` char(36) NOT NULL,
  \`symbol\` varchar(64) DEFAULT NULL,
  \`side\` varchar(10) DEFAULT NULL,
  \`order_type\` varchar(64) DEFAULT NULL,
  \`trigger_type\` varchar(64) DEFAULT NULL,
  \`status\` varchar(32) NOT NULL DEFAULT 'OPEN',
  \`leverage\` double DEFAULT NULL,
  \`quantity\` decimal(30,12) DEFAULT NULL,
  \`order_price\` decimal(30,12) DEFAULT NULL,
  \`stoploss_price\` decimal(30,12) DEFAULT NULL,
  \`takeprofit_price\` decimal(30,12) DEFAULT NULL,
  \`reduce_only\` tinyint(1) NOT NULL DEFAULT '0',
  \`payload_json\` json DEFAULT NULL,
  \`canceled_at\` timestamp NULL DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  KEY \`idx_paper_orders_user_status_created_at\` (\`user_id\`,\`status\`,\`created_at\`),
  KEY \`idx_paper_orders_account_created_at\` (\`account_id\`,\`created_at\`),
  KEY \`idx_paper_orders_suggested_trade_id\` (\`suggested_trade_id\`),
  CONSTRAINT \`fk_paper_orders_suggested_trade\` FOREIGN KEY (\`suggested_trade_id\`) REFERENCES \`suggested_trades\` (\`id\`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`suggested_trade_executions\` (
  \`suggested_trade_id\` char(36) NOT NULL,
  \`user_id\` char(36) NOT NULL,
  \`execution_mode\` varchar(16) DEFAULT NULL,
  \`pre_trade_check_id\` char(36) DEFAULT NULL,
  \`pre_trade_state\` varchar(20) DEFAULT NULL,
  \`pre_trade_checked_at\` timestamp NULL DEFAULT NULL,
  \`pre_trade_blocked_reason\` text,
  \`accepted_by\` varchar(16) DEFAULT NULL,
  \`accepted_at\` timestamp NULL DEFAULT NULL,
  \`order_id\` varchar(191) DEFAULT NULL,
  \`paper_order_id\` char(36) DEFAULT NULL,
  \`broker_key\` varchar(100) DEFAULT NULL,
  \`account_id\` char(36) DEFAULT NULL,
  \`order_status\` varchar(64) DEFAULT NULL,
  \`paper_order_status\` varchar(64) DEFAULT NULL,
  \`execution_state\` varchar(32) DEFAULT NULL,
  \`order_type\` varchar(64) DEFAULT NULL,
  \`trigger_type\` varchar(64) DEFAULT NULL,
  \`leverage\` double DEFAULT NULL,
  \`quantity\` double DEFAULT NULL,
  \`entry_price\` decimal(30,12) DEFAULT NULL,
  \`stop_loss_price\` decimal(30,12) DEFAULT NULL,
  \`take_profit_price\` decimal(30,12) DEFAULT NULL,
  \`protection_state\` varchar(32) DEFAULT NULL,
  \`protection_source\` varchar(64) DEFAULT NULL,
  \`protection_plan_json\` json DEFAULT NULL,
  \`route_attempts_json\` json DEFAULT NULL,
  \`protection_attempts\` int unsigned NOT NULL DEFAULT '0',
  \`protection_last_error\` text,
  \`protection_checked_at\` timestamp NULL DEFAULT NULL,
  \`protection_attached_at\` timestamp NULL DEFAULT NULL,
  \`submitted_at\` timestamp NULL DEFAULT NULL,
  \`linked_at\` timestamp NULL DEFAULT NULL,
  \`last_seen_at\` timestamp NULL DEFAULT NULL,
  \`filled_at\` timestamp NULL DEFAULT NULL,
  \`canceled_at\` timestamp NULL DEFAULT NULL,
  \`filled_price\` decimal(30,12) DEFAULT NULL,
  \`filled_quantity\` double DEFAULT NULL,
  \`remaining_quantity\` double DEFAULT NULL,
  \`position_id\` varchar(191) DEFAULT NULL,
  \`position_status\` varchar(64) DEFAULT NULL,
  \`position_opened_at\` timestamp NULL DEFAULT NULL,
  \`position_closed_at\` timestamp NULL DEFAULT NULL,
  \`exit_price\` decimal(30,12) DEFAULT NULL,
  \`realized_pnl\` decimal(30,12) DEFAULT NULL,
  \`outcome\` varchar(24) DEFAULT NULL,
  \`note\` text,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`suggested_trade_id\`),
  KEY \`idx_suggested_trade_executions_user_order_lookup\` (\`user_id\`,\`broker_key\`,\`account_id\`,\`order_id\`),
  KEY \`idx_suggested_trade_executions_user_paper_order_lookup\` (\`user_id\`,\`paper_order_id\`),
  KEY \`idx_suggested_trade_executions_user_position_lookup\` (\`user_id\`,\`broker_key\`,\`account_id\`,\`position_id\`),
  KEY \`idx_suggested_trade_executions_user_state_seen_at\` (\`user_id\`,\`broker_key\`,\`account_id\`,\`execution_state\`,\`last_seen_at\`),
  KEY \`idx_suggested_trade_executions_protection_state\` (\`user_id\`,\`broker_key\`,\`account_id\`,\`protection_state\`,\`updated_at\`),
  KEY \`idx_suggested_trade_executions_pre_trade_state\` (\`user_id\`,\`pre_trade_state\`,\`updated_at\`),
  KEY \`idx_suggested_trade_executions_pre_trade_check\` (\`pre_trade_check_id\`),
  CONSTRAINT \`fk_suggested_trade_executions_trade\` FOREIGN KEY (\`suggested_trade_id\`) REFERENCES \`suggested_trades\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`trades\` (
  \`id\` varchar(36) NOT NULL,
  \`strategy\` varchar(100) NOT NULL,
  \`symbol\` varchar(50) NOT NULL,
  \`interval\` varchar(20) NOT NULL,
  \`side\` varchar(10) NOT NULL,
  \`alertOpenTime\` bigint NOT NULL,
  \`confirmOpenTime\` bigint NOT NULL,
  \`alertHigh\` varchar(50) NOT NULL,
  \`alertLow\` varchar(50) NOT NULL,
  \`confirmClose\` varchar(50) NOT NULL,
  \`barsWaited\` int unsigned NOT NULL,
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uq_trades_dedup\` (\`strategy\`,\`symbol\`,\`interval\`,\`side\`,\`alertOpenTime\`,\`confirmOpenTime\`),
  KEY \`idx_trades_symbol_interval\` (\`symbol\`,\`interval\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`users\` (
  \`id\` varchar(36) NOT NULL,
  \`email\` varchar(191) NOT NULL,
  \`password_hash\` varchar(255) NOT NULL,
  \`full_name\` varchar(191) NOT NULL,
  \`role\` varchar(64) NOT NULL DEFAULT 'Trader',
  \`status\` varchar(32) NOT NULL DEFAULT 'active',
  \`last_login_at\` timestamp NULL DEFAULT NULL,
  \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`funds_snapshots\` (
  \`id\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`broker_key\` varchar(100) NOT NULL,
  \`account_id\` char(36) NOT NULL,
  \`wallet_funds_json\` json DEFAULT NULL,
  \`futures_funds_json\` json DEFAULT NULL,
  \`computed_at\` timestamp NOT NULL,
  \`snapshot_date\` date NOT NULL,
  \`observed_at\` timestamp NULL DEFAULT NULL,
  \`last_attempt_at\` timestamp NOT NULL,
  \`fetch_status\` varchar(20) NOT NULL,
  \`error_message\` text,
  \`source\` varchar(100) NOT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_funds_snapshots_user_account_day\` (\`user_id\`,\`broker_key\`,\`account_id\`,\`snapshot_date\`),
  KEY \`idx_funds_snapshots_user_computed\` (\`user_id\`,\`computed_at\`),
  KEY \`idx_funds_snapshots_user_broker_account\` (\`user_id\`,\`broker_key\`,\`account_id\`),
  KEY \`idx_funds_snapshots_user_status_attempt\` (\`user_id\`,\`fetch_status\`,\`last_attempt_at\`),
  KEY \`idx_funds_snapshots_user_broker_account_attempt\` (\`user_id\`,\`broker_key\`,\`account_id\`,\`last_attempt_at\`),
  CONSTRAINT \`fk_funds_snapshots_user_id\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`refresh_tokens\` (
  \`id\` varchar(36) NOT NULL,
  \`token_hash\` char(64) NOT NULL,
  \`user_id\` varchar(255) NOT NULL,
  \`expires_at\` timestamp NOT NULL,
  \`revoked_at\` timestamp NULL DEFAULT NULL,
  \`user_agent\` varchar(255) DEFAULT NULL,
  \`ip_address\` varchar(64) DEFAULT NULL,
  \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_a7838d2ba25be1342091b6695f\` (\`token_hash\`),
  KEY \`IDX_3ddc983c5f7bcf132fd8732c3f\` (\`user_id\`),
  CONSTRAINT \`FK_3ddc983c5f7bcf132fd8732c3f4\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`risk_alerts\` (
  \`id\` char(36) NOT NULL,
  \`snapshotId\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`severity\` varchar(20) NOT NULL,
  \`message\` varchar(255) NOT NULL,
  \`symbol\` varchar(50) NOT NULL,
  \`channel\` varchar(50) DEFAULT NULL,
  \`status\` varchar(30) DEFAULT NULL,
  \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updatedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  KEY \`idx_risk_alerts_snapshot_created_at\` (\`snapshotId\`,\`createdAt\`),
  KEY \`IDX_risk_alerts_USER_ID\` (\`user_id\`),
  CONSTRAINT \`fk_risk_alerts_snapshot_id\` FOREIGN KEY (\`snapshotId\`) REFERENCES \`risk_snapshots\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`FK_risk_alerts_USER_ID\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`risk_controls\` (
  \`id\` char(36) NOT NULL,
  \`snapshotId\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`bucket\` varchar(255) NOT NULL,
  \`exposure\` varchar(100) NOT NULL,
  \`threshold\` varchar(100) NOT NULL,
  \`status\` varchar(30) NOT NULL,
  \`action\` varchar(255) NOT NULL,
  \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updatedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  KEY \`idx_risk_controls_snapshot_status\` (\`snapshotId\`,\`status\`),
  KEY \`IDX_risk_controls_USER_ID\` (\`user_id\`),
  CONSTRAINT \`fk_risk_controls_snapshot_id\` FOREIGN KEY (\`snapshotId\`) REFERENCES \`risk_snapshots\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`FK_risk_controls_USER_ID\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`risk_scenarios\` (
  \`id\` char(36) NOT NULL,
  \`snapshotId\` char(36) NOT NULL,
  \`user_id\` varchar(191) NOT NULL,
  \`scenario\` varchar(120) NOT NULL,
  \`impact\` varchar(60) NOT NULL,
  \`commentary\` varchar(255) NOT NULL,
  \`createdAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updatedAt\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  KEY \`idx_risk_scenarios_snapshot_created\` (\`snapshotId\`,\`createdAt\`),
  KEY \`idx_risk_scenarios_user_created\` (\`user_id\`,\`createdAt\`),
  CONSTRAINT \`fk_risk_scenarios_snapshot_id\` FOREIGN KEY (\`snapshotId\`) REFERENCES \`risk_snapshots\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`FK_risk_scenarios_USER_ID\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`scheduler_user_configs\` (
  \`id\` char(36) NOT NULL,
  \`scheduler_key\` varchar(100) NOT NULL,
  \`user_id\` char(36) NOT NULL,
  \`name\` varchar(191) NOT NULL,
  \`description\` varchar(255) DEFAULT NULL,
  \`enabled\` tinyint(1) NOT NULL DEFAULT '0',
  \`cron_expression\` varchar(64) NOT NULL,
  \`timezone\` varchar(64) NOT NULL DEFAULT 'Asia/Kolkata',
  \`run_at\` varchar(5) NOT NULL DEFAULT '01:00',
  \`interval_days\` int NOT NULL DEFAULT '1',
  \`batch_size\` int NOT NULL DEFAULT '200',
  \`scheduler_type\` varchar(16) NOT NULL DEFAULT 'user',
  \`config\` text,
  \`last_started_at\` timestamp NULL DEFAULT NULL,
  \`last_finished_at\` timestamp NULL DEFAULT NULL,
  \`last_status\` varchar(32) DEFAULT NULL,
  \`last_error\` text,
  \`running_lock_until\` timestamp NULL DEFAULT NULL,
  \`created_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  \`updated_at\` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_scheduler_user_configs_scheduler_user\` (\`scheduler_key\`,\`user_id\`),
  KEY \`idx_scheduler_user_configs_user_scheduler\` (\`user_id\`,\`scheduler_key\`),
  KEY \`idx_scheduler_user_configs_scheduler_enabled\` (\`scheduler_key\`,\`enabled\`),
  CONSTRAINT \`fk_scheduler_user_configs_scheduler_key\` FOREIGN KEY (\`scheduler_key\`) REFERENCES \`scheduler_configs\` (\`key\`) ON DELETE CASCADE,
  CONSTRAINT \`fk_scheduler_user_configs_user_id\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`watchlists\` (
  \`id\` varchar(36) NOT NULL,
  \`name\` varchar(255) NOT NULL,
  \`type\` varchar(30) NOT NULL,
  \`description\` text,
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`user_id\` varchar(191) NOT NULL,
  \`normalized_name\` varchar(255) GENERATED ALWAYS AS (nullif(lower(trim(\`name\`)),_utf8mb4'')) STORED,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_watchlists_id_user_id\` (\`id\`,\`user_id\`),
  UNIQUE KEY \`uidx_watchlists_owner_name_ci\` (\`user_id\`,\`normalized_name\`),
  KEY \`idx_watchlists_type_updated_at\` (\`type\`,\`updatedAt\`),
  KEY \`idx_watchlists_user_updated_at\` (\`user_id\`,\`updatedAt\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
    `CREATE TABLE \`watchlist_items\` (
  \`id\` varchar(36) NOT NULL,
  \`watchlistId\` varchar(36) NOT NULL,
  \`symbol\` varchar(50) NOT NULL,
  \`regime\` varchar(50) DEFAULT NULL,
  \`signal\` varchar(100) DEFAULT NULL,
  \`aiScore\` int unsigned DEFAULT NULL,
  \`change24h\` double DEFAULT NULL,
  \`volume24h\` double DEFAULT NULL,
  \`setup\` varchar(100) DEFAULT NULL,
  \`status\` varchar(30) DEFAULT NULL,
  \`alerts\` int unsigned NOT NULL DEFAULT '0',
  \`liquidity\` varchar(30) DEFAULT NULL,
  \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`user_id\` varchar(191) NOT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uidx_watchlist_items_owner_watchlist_symbol\` (\`user_id\`,\`watchlistId\`,\`symbol\`),
  KEY \`idx_watchlist_items_status_updated_at\` (\`status\`,\`updatedAt\`),
  KEY \`idx_watchlist_items_watchlist_symbol\` (\`watchlistId\`,\`symbol\`),
  KEY \`idx_watchlist_items_user_watchlist_updated_at\` (\`user_id\`,\`watchlistId\`,\`updatedAt\`),
  KEY \`fk_watchlist_items_watchlist_owner\` (\`watchlistId\`,\`user_id\`),
  CONSTRAINT \`FK_710da2b72379823ed515e5ea9eb\` FOREIGN KEY (\`watchlistId\`) REFERENCES \`watchlists\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`fk_watchlist_items_watchlist_owner\` FOREIGN KEY (\`watchlistId\`, \`user_id\`) REFERENCES \`watchlists\` (\`id\`, \`user_id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci`,
  ];

  private readonly dropTables = [
    'watchlist_items',
    'watchlists',
    'scheduler_user_configs',
    'risk_scenarios',
    'risk_controls',
    'risk_alerts',
    'refresh_tokens',
    'funds_snapshots',
    'users',
    'trades',
    'suggested_trade_executions',
    'paper_orders',
    'automation_run_outputs',
    'suggested_trades',
    'signal_alert_links',
    'signal_actions',
    'signals',
    'settings_audit_logs',
    'scheduler_sync_pending_records',
    'scheduler_sync_checkpoints',
    'scheduler_health_check_results',
    'exchange_asset_update_logs',
    'scheduler_run_logs',
    'scheduler_run_locks',
    'scheduler_positions_snapshots',
    'scheduler_orders_snapshots',
    'scheduler_configs',
    'scheduler_commands',
    'risk_snapshots',
    'risk_snapshot_source_coverage',
    'risk_snapshot_policy_contexts',
    'risk_rule_evaluations',
    'risk_request_scope_impacts',
    'risk_request_rule_evaluations',
    'risk_request_checks',
    'risk_position_snapshots',
    'risk_policy_versions',
    'risk_policies',
    'risk_order_snapshots',
    'risk_broker_snapshots',
    'risk_broker_asset_snapshots',
    'risk_asset_snapshots',
    'risk_account_snapshots',
    'position_read_models',
    'portfolio_holdings',
    'portfolio_snapshots',
    'order_submission_requests',
    'market_symbol_snapshots',
    'exchanges',
    'email_deliveries',
    'broker_accounts',
    'connections',
    'broker_assets',
    'brokers',
    'automation_events',
    'automation_alerts',
    'automations',
    'automation_runs',
    'automation_cursors',
    'assets',
    'asset_price',
    'app_settings',
    'alert_actions',
    'alerts',
    'activity_saved_views',
    'activity_logs',
    'activity_exports',
  ];

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const statement of this.createStatements) {
      await queryRunner.query(statement);
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('SET FOREIGN_KEY_CHECKS = 0');
    try {
      for (const tableName of this.dropTables) {
        await queryRunner.query(`DROP TABLE IF EXISTS \`${tableName}\``);
      }
    } finally {
      await queryRunner.query('SET FOREIGN_KEY_CHECKS = 1');
    }
  }
}
